### ISSUE TITLE
Bagfile writing to local file system, examples

### ISSUE THREAD

**Issue by inactivist** [foxglove/rosbag2-web#6]
> ROS2 (Robot Operating System) bag reader and writer for the browser

Though the README.md file describes this as a reader and writer, I see no examples of serializing to a bag file.   (Unsure if I'm misinterpreting the description & package scope.)

Is writing to an opened [FileSystemWritableFileStream](https://wicg.github.io/file-system-access/#api-filesystemwritablefilestream) stream  available elsewhere, or planned for this package?

**Comment by defunctzombie** [comment]
@jhurliman can confirm - but I think thats an unfortunate copy/paste from another README we have (https://github.com/foxglove/rosmsg-serialization). Our rosbag repos only support reading.

**Comment by jhurliman** [comment]
I've updated the README to reflect that this is a read-only library
